modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="the_transcendeum"
version="0.2.0"
displayName="The Transcendeum"
credits="Texturers: Sajevius, Aqu, Dylanvhs, Ddx11, Lyof / Coders: Aqu, Sajevius / Ideas: everyone from Team Lodestar / Special thanks: MCreator, for making this mod possible!"
displayURL="https://team-lodestar.github.io"
logoFile="logo.png"
authors="Team Lodestar"
description='''
Uncover and venture upon a new magnificent, alternate-Overworld dimension transcended beyond normal reality.
'''

[[dependencies.the_transcendeum]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




